# coding: utf-8

"""
    AutoRoll

    This is a description of my AutoRoll servise, which allows you rent a car.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: viranilla7@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.admin import Admin  # noqa: E501
from swagger_client.rest import ApiException


class TestAdmin(unittest.TestCase):
    """Admin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdmin(self):
        """Test Admin"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.admin.Admin()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
