# coding: utf-8

"""
    AutoRoll

    This is a description of my AutoRoll servise, which allows you rent a car.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: viranilla7@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.rent import Rent  # noqa: E501
from swagger_client.rest import ApiException


class TestRent(unittest.TestCase):
    """Rent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRent(self):
        """Test Rent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.rent.Rent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
