# coding: utf-8

"""
    AutoRoll

    This is a description of my AutoRoll servise, which allows you rent a car.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: viranilla7@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.car_api import CarApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCarApi(unittest.TestCase):
    """CarApi unit test stubs"""

    def setUp(self):
        self.api = CarApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_car(self):
        """Test case for add_car

        Add a new car to the store  # noqa: E501
        """
        pass

    def test_delete_car(self):
        """Test case for delete_car

        Deletes a car  # noqa: E501
        """
        pass

    def test_find_cars_by_status(self):
        """Test case for find_cars_by_status

        Finds cars by status  # noqa: E501
        """
        pass

    def test_get_car_by_id(self):
        """Test case for get_car_by_id

        Find car by ID  # noqa: E501
        """
        pass

    def test_update_car(self):
        """Test case for update_car

        Update an existing car  # noqa: E501
        """
        pass

    def test_update_car_with_form(self):
        """Test case for update_car_with_form

        Updates a car in the store with form data  # noqa: E501
        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        uploads an image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
