# coding: utf-8

"""
    AutoRoll

    This is a description of my AutoRoll servise, which allows you rent a car.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: viranilla7@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.admin_api import AdminApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_admin(self):
        """Test case for create_admin

        Create admin  # noqa: E501
        """
        pass

    def test_create_admins_with_list_input(self):
        """Test case for create_admins_with_list_input

        Creates list of adminS with given input array  # noqa: E501
        """
        pass

    def test_delete_admin(self):
        """Test case for delete_admin

        Delete user  # noqa: E501
        """
        pass

    def test_get_admin_by_name(self):
        """Test case for get_admin_by_name

        Get admin by username  # noqa: E501
        """
        pass

    def test_login_admin(self):
        """Test case for login_admin

        Logs admin into the system  # noqa: E501
        """
        pass

    def test_logout_admin(self):
        """Test case for logout_admin

        Logs out current logged in admin session  # noqa: E501
        """
        pass

    def test_update_admin(self):
        """Test case for update_admin

        Updated admin  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
