"""add models

Revision ID: 893beb1744d5
Revises: 7f2f07a29b65
Create Date: 2020-12-06 19:57:28.854828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893beb1744d5'
down_revision = '7f2f07a29b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
